publication_categories = {
    "Books and Documents": [
        "Address",
        "Autobiography",
        "Bibliography",
        "Biography",
        "Case Reports",
        "Classical Article",
        "Collected Work",
        "Congress",
        "Corrected and Republished Article",
        "Dataset",
        "Dictionary",
        "Directory",
        "Duplicate Publication",
        "Editorial",
        "Electronic Supplementary Materials",
        "English Abstract",
        "Festschrift",
        "Government Publication",
        "Guideline",
        "Historical Article",
        "Interview",
        "Journal Article",
        "Lecture",
        "Legal Case",
        "Legislation",
        "Letter",
        "News",
        "Newspaper Article",
        "Patient Education Handout",
        "Periodical Index",
        "Personal Narrative",
        "Portrait",
        "Preprint",
        "Published Erratum",
        "Research Support, N.I.H., Extramural",
        "Research Support, N.I.H., Intramural",
        "Research Support, Non-U.S. Gov't",
        "Research Support, U.S. Gov't, Non-P.H.S.",
        "Research Support, U.S. Gov't, P.H.S.",
        "Technical Report",
        "Video-Audio Media",
        "Webcast"
    ],
    "Meta Analysis": [
        "Meta-Analysis",
        "Systematic Review"
    ],
    "Review": [
        "Comparative Study",
        "Comment",
        "Consensus Development Conference",
        "Consensus Development Conference, NIH",
        "Evaluation Study",
        "Expression of Concern",
        "Guideline",
        "Introductory Journal Article",
        "Multicenter Study",
        "Observational Study",
        "Observational Study, Veterinary",
        "Overall",
        "Practice Guideline",
        "Review",
        "Scientific Integrity Review",
        "Validation Study"
    ],
    "Clinical Trials": [
        "Adaptive Clinical Trial",
        "Clinical Study",
        "Clinical Trial",
        "Clinical Trial, Phase I",
        "Clinical Trial, Phase II",
        "Clinical Trial, Phase III",
        "Clinical Trial, Phase IV",
        "Clinical Trial Protocol",
        "Clinical Trial, Veterinary",
        "Controlled Clinical Trial",
        "Equivalence Trial",
        "Pragmatic Clinical Trial",
        "Randomized Controlled Trial",
        "Randomized Controlled Trial, Veterinary"
    ]
}